# Generated by Django 3.2.22 on 2023-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_dbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=15)),
                ('apass', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LocMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locimage', models.ImageField(default='', upload_to='location_img')),
                ('loc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='turf_dbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=25)),
                ('tprice', models.IntegerField()),
                ('tstime', models.CharField(max_length=10)),
                ('tetime', models.CharField(max_length=10)),
                ('tloc', models.CharField(max_length=25)),
                ('tarea', models.CharField(max_length=50)),
                ('taddress', models.URLField(max_length=25)),
                ('features', models.BooleanField(default='False')),
                ('features2', models.BooleanField(default='False')),
                ('timage1', models.ImageField(default='', upload_to='turf_img')),
                ('timage2', models.ImageField(default='', upload_to='turf_img')),
                ('timage3', models.ImageField(default='', upload_to='turf_img')),
            ],
        ),
    ]
