# Generated by Django 3.2.22 on 2023-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_auto_20231120_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_dbs',
            name='features',
            field=models.TextField(default=''),
        ),
    ]
