# Generated by Django 3.2.22 on 2023-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0007_auto_20231124_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_dbs',
            name='tname',
            field=models.CharField(max_length=100),
        ),
    ]
