# Generated by Django 3.2.22 on 2023-11-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_App', '0002_manager_signup_mphone'),
        ('Admin_App', '0008_alter_turf_dbs_tname'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_dbs',
            name='tmanagerid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Manager_App.manager_signup'),
        ),
    ]
