# Generated by Django 3.2.22 on 2023-11-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager_App', '0002_manager_signup_mphone'),
        ('Admin_App', '0009_turf_dbs_tmanagerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_dbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254)),
                ('usubject', models.CharField(max_length=15)),
                ('umessage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BookTurf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField()),
                ('bstime', models.TimeField()),
                ('betime', models.TimeField()),
                ('duration', models.IntegerField()),
                ('btotal', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('mid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager_App.manager_signup')),
                ('turfid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin_App.turf_dbs')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_App.signup')),
            ],
        ),
    ]
