# Generated by Django 3.2.22 on 2023-11-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookturf',
            name='mid',
        ),
    ]
