# Generated by Django 3.2.22 on 2023-11-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_App', '0002_manager_signup_mphone'),
        ('User_App', '0002_remove_bookturf_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookturf',
            name='mid',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager_App.manager_signup'),
        ),
    ]
