# Generated by Django 3.2.22 on 2023-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50)),
                ('memail', models.EmailField(max_length=254)),
                ('mloc', models.CharField(max_length=100)),
                ('mpass', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
